name: phantom-inventory-classifier-env
channels:
  - defaults
dependencies:
  - python=3.11.8
  - pandas=2.2.3
  - numpy=1.26.4
  - scikit-learn=1.5.2
  - lightgbm=4.5.0
  - joblib=1.2.0
  - PyYAML=6.0.1